var mime_samples = [
  { 'mime': 'application/binary', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/Flash/add.fla', 'dir': '_m0/0', 'linked': 2, 'len': 154624 },
    { 'url': 'http://testphp.vulnweb.com/Flash/add.swf', 'dir': '_m0/1', 'linked': 2, 'len': 17418 } ]
  },
  { 'mime': 'application/javascript', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/admin/create.sql', 'dir': '_m1/0', 'linked': 2, 'len': 523 },
    { 'url': 'http://testphp.vulnweb.com/pictures/credentials.txt', 'dir': '_m1/1', 'linked': 2, 'len': 33 } ]
  },
  { 'mime': 'application/xhtml+xml', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/', 'dir': '_m2/0', 'linked': 2, 'len': 4096 },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'dir': '_m2/1', 'linked': 2, 'len': 4673 },
    { 'url': 'http://testphp.vulnweb.com/signup.php', 'dir': '_m2/2', 'linked': 2, 'len': 5183 },
    { 'url': 'http://testphp.vulnweb.com/AJAX/', 'dir': '_m2/3', 'linked': 2, 'len': 4236 },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/', 'dir': '_m2/4', 'linked': 0, 'len': 263 },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/server-status', 'dir': '_m2/5', 'linked': 0, 'len': 1818 },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin.bak/', 'dir': '_m2/6', 'linked': 0, 'len': 264 },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-unix.html', 'dir': '_m2/7', 'linked': 2, 'len': 3936 },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'dir': '_m2/8', 'linked': 5, 'len': 415 },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'dir': '_m2/9', 'linked': 5, 'len': 765 },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'dir': '_m2/10', 'linked': 0, 'len': 504 },
    { 'url': 'http://testphp.vulnweb.com/artists.php?artist=1', 'dir': '_m2/11', 'linked': 2, 'len': 5384 },
    { 'url': 'http://testphp.vulnweb.com/categories.php', 'dir': '_m2/12', 'linked': 2, 'len': 5248 },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'dir': '_m2/13', 'linked': 5, 'len': 1462 },
    { 'url': 'http://testphp.vulnweb.com/comment.php?aid=1', 'dir': '_m2/14', 'linked': 1, 'len': 1252 },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'dir': '_m2/15', 'linked': 5, 'len': 565 },
    { 'url': 'http://testphp.vulnweb.com/disclaimer.php', 'dir': '_m2/16', 'linked': 2, 'len': 4667 },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=1', 'dir': '_m2/17', 'linked': 2, 'len': 7125 },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=1', 'dir': '_m2/18', 'linked': 2, 'len': 5567 },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'dir': '_m2/19', 'linked': 0, 'len': 6499 } ]
  },
  { 'mime': 'image/gif', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/images/logo.gif', 'dir': '_m3/0', 'linked': 2, 'len': 6660 },
    { 'url': 'http://testphp.vulnweb.com/images/remark.gif', 'dir': '_m3/1', 'linked': 2, 'len': 79 } ]
  },
  { 'mime': 'image/jpeg', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/1.jpg', 'dir': '_m4/0', 'linked': 2, 'len': 3551 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/2.jpg', 'dir': '_m4/1', 'linked': 2, 'len': 2739 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/3.jpg', 'dir': '_m4/2', 'linked': 2, 'len': 3560 },
    { 'url': 'http://testphp.vulnweb.com/pictures/1.jpg', 'dir': '_m4/3', 'linked': 2, 'len': 12426 },
    { 'url': 'http://testphp.vulnweb.com/pictures/1.jpg.tn', 'dir': '_m4/4', 'linked': 2, 'len': 4355 },
    { 'url': 'http://testphp.vulnweb.com/pictures/2.jpg', 'dir': '_m4/5', 'linked': 2, 'len': 3324 },
    { 'url': 'http://testphp.vulnweb.com/pictures/2.jpg.tn', 'dir': '_m4/6', 'linked': 2, 'len': 1353 },
    { 'url': 'http://testphp.vulnweb.com/pictures/3.jpg', 'dir': '_m4/7', 'linked': 2, 'len': 9692 },
    { 'url': 'http://testphp.vulnweb.com/pictures/3.jpg.tn', 'dir': '_m4/8', 'linked': 2, 'len': 3725 },
    { 'url': 'http://testphp.vulnweb.com/pictures/4.jpg', 'dir': '_m4/9', 'linked': 2, 'len': 13969 },
    { 'url': 'http://testphp.vulnweb.com/pictures/4.jpg.tn', 'dir': '_m4/10', 'linked': 2, 'len': 4615 },
    { 'url': 'http://testphp.vulnweb.com/pictures/5.jpg', 'dir': '_m4/11', 'linked': 2, 'len': 14228 },
    { 'url': 'http://testphp.vulnweb.com/pictures/5.jpg.tn', 'dir': '_m4/12', 'linked': 2, 'len': 4428 },
    { 'url': 'http://testphp.vulnweb.com/pictures/6.jpg.tn', 'dir': '_m4/13', 'linked': 2, 'len': 4345 },
    { 'url': 'http://testphp.vulnweb.com/pictures/7.jpg', 'dir': '_m4/14', 'linked': 2, 'len': 19219 },
    { 'url': 'http://testphp.vulnweb.com/pictures/7.jpg.tn', 'dir': '_m4/15', 'linked': 2, 'len': 6458 },
    { 'url': 'http://testphp.vulnweb.com/pictures/8.jpg', 'dir': '_m4/16', 'linked': 2, 'len': 50299 },
    { 'url': 'http://testphp.vulnweb.com/pictures/8.jpg.tn', 'dir': '_m4/17', 'linked': 2, 'len': 4139 } ]
  },
  { 'mime': 'text/css', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'dir': '_m5/0', 'linked': 2, 'len': 562 },
    { 'url': 'http://testphp.vulnweb.com/style.css', 'dir': '_m5/1', 'linked': 2, 'len': 5482 } ]
  },
  { 'mime': 'text/html', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/sfi9876', 'dir': '_m6/0', 'linked': 2, 'len': 168 },
    { 'url': 'http://testphp.vulnweb.com/admin/', 'dir': '_m6/1', 'linked': 2, 'len': 278 },
    { 'url': 'http://testphp.vulnweb.com/CVS/', 'dir': '_m6/2', 'linked': 2, 'len': 611 },
    { 'url': 'http://testphp.vulnweb.com/Flash/', 'dir': '_m6/3', 'linked': 2, 'len': 387 },
    { 'url': 'http://testphp.vulnweb.com/hpp/', 'dir': '_m6/4', 'linked': 5, 'len': 203 },
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=12--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000488v335985\x3e', 'dir': '_m6/5', 'linked': 2, 'len': 482 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'dir': '_m6/6', 'linked': 2, 'len': 975 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php', 'dir': '_m6/7', 'linked': 1, 'len': 47 },
    { 'url': 'http://testphp.vulnweb.com/pictures/', 'dir': '_m6/8', 'linked': 2, 'len': 2685 },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-win.html', 'dir': '_m6/9', 'linked': 2, 'len': 698 },
    { 'url': 'http://testphp.vulnweb.com/pictures/WS_FTP.LOG', 'dir': '_m6/10', 'linked': 2, 'len': 771 } ]
  },
  { 'mime': 'text/plain', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/CVS/Repository', 'dir': '_m7/0', 'linked': 2, 'len': 8 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/.htaccess', 'dir': '_m7/1', 'linked': 0, 'len': 176 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php', 'dir': '_m7/2', 'linked': 1, 'len': 6 },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'dir': '_m7/3', 'linked': 1, 'len': 136 },
    { 'url': 'http://testphp.vulnweb.com/pictures/wp-config.bak', 'dir': '_m7/4', 'linked': 2, 'len': 1535 },
    { 'url': 'http://testphp.vulnweb.com/privacy.php', 'dir': '_m7/5', 'linked': 2, 'len': 16 },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'dir': '_m7/6', 'linked': 2, 'len': 377 },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'dir': '_m7/7', 'linked': 5, 'len': 14 } ]
  },
  { 'mime': 'text/xml', 'samples': [
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'dir': '_m8/0', 'linked': 2, 'len': 345 } ]
  }
];

var issue_samples = [
  { 'severity': 4, 'type': 50107, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=http://www.google.com/humans.txt%23foo%3D', 'extra': 'remote file inclusion', 'sid': '0', 'dir': '_i0/0' } ]
  },
  { 'severity': 4, 'type': 50103, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'response to \x27\x27\x27\x27\x22\x22\x22\x22 different than to \x27\x22\x27\x22\x27\x22\x27\x22', 'sid': '0', 'dir': '_i1/0' },
    { 'url': 'http://testphp.vulnweb.com/artists.php?artist=1-0', 'extra': 'response suggests arithmetic evaluation on server side (type 1)', 'sid': '0', 'dir': '_i1/1' },
    { 'url': 'http://testphp.vulnweb.com/artists.php?artist=1%200%200%20-%20-', 'extra': 'response suggests arithmetic evaluation on server side (type 2)', 'sid': '0', 'dir': '_i1/2' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=1-0', 'extra': 'response suggests arithmetic evaluation on server side (type 1)', 'sid': '0', 'dir': '_i1/3' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=1%200%200%20-%20-', 'extra': 'response suggests arithmetic evaluation on server side (type 2)', 'sid': '0', 'dir': '_i1/4' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=1-0', 'extra': 'response suggests arithmetic evaluation on server side (type 1)', 'sid': '0', 'dir': '_i1/5' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=1%200%200%20-%20-', 'extra': 'response suggests arithmetic evaluation on server side (type 2)', 'sid': '0', 'dir': '_i1/6' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=1-0', 'extra': 'response suggests arithmetic evaluation on server side (type 1)', 'sid': '0', 'dir': '_i1/7' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=1%200%200%20-%20-', 'extra': 'response suggests arithmetic evaluation on server side (type 2)', 'sid': '0', 'dir': '_i1/8' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'response to \x27\x27\x27\x27\x22\x22\x22\x22 different than to \x27\x22\x27\x22\x27\x22\x27\x22', 'sid': '0', 'dir': '_i1/9' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'response to \x27\x27\x27\x27\x22\x22\x22\x22 different than to \x27\x22\x27\x22\x27\x22\x27\x22', 'sid': '0', 'dir': '_i1/10' } ]
  },
  { 'severity': 3, 'type': 40402, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/0' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/1' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/2' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/3' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/4' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/5' },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-unix.html', 'extra': 'PHP notice (HTML)', 'sid': '22012', 'dir': '_i2/6' },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-unix.html', 'extra': 'PHP warning (HTML)', 'sid': '22018', 'dir': '_i2/7' },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-win.html', 'extra': 'PHP notice (HTML)', 'sid': '22012', 'dir': '_i2/8' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/9' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/10' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/11' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/12' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/13' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/14' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/15' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'SQL syntax error', 'sid': '21011', 'dir': '_i2/16' },
    { 'url': 'http://testphp.vulnweb.com/artists.php?artist=9876sfi', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/17' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/18' },
    { 'url': 'http://testphp.vulnweb.com/comment.php?[0][\x27aid\x27]=1', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/19' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/20' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/21' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/22' },
    { 'url': 'http://testphp.vulnweb.com/comment.php?[0][\x27pid\x27]=1', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/23' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/24' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/25' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/26' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/27' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/28' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=9876sfi', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/29' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?[0][\x27artist\x27]=1', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/30' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=.../1', 'extra': 'SQL syntax error', 'sid': '21011', 'dir': '_i2/31' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=9876sfi', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/32' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?[0][\x27cat\x27]=1', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/33' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=.../1', 'extra': 'SQL syntax error', 'sid': '21011', 'dir': '_i2/34' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=9876sfi', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/35' },
    { 'url': 'http://testphp.vulnweb.com/search.php', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/36' },
    { 'url': 'http://testphp.vulnweb.com/search.php?[0][\x27test\x27]=query', 'extra': 'PHP notice (text)', 'sid': '22013', 'dir': '_i2/37' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=\x27skip\x27\x27\x27\x22fish\x22\x22\x22', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/38' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/39' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/40' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i2/41' } ]
  },
  { 'severity': 3, 'type': 40304, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=12--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000488v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i3/0' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000060v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i3/1' } ]
  },
  { 'severity': 3, 'type': 40301, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000060v335985\x3e', 'extra': 'text/plain', 'sid': '0', 'dir': '_i4/0' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'extra': 'text/xml', 'sid': '0', 'dir': '_i4/1' } ]
  },
  { 'severity': 3, 'type': 40101, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=12--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000488v335985\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/0' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/1' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/2' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/3' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/4' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/5' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/6' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/7' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/8' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/9' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/10' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/11' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/12' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000525v335985\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/13' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=1--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000132v335985\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/14' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/15' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000060v335985\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i5/16' } ]
  },
  { 'severity': 2, 'type': 30909, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/server-status', 'extra': 'Apache mod_status page detected', 'sid': '11004', 'dir': '_i6/0' } ]
  },
  { 'severity': 2, 'type': 30601, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/0' },
    { 'url': 'http://testphp.vulnweb.com/hpp/params.php?aaaa/=', 'extra': '', 'sid': '0', 'dir': '_i7/1' },
    { 'url': 'http://testphp.vulnweb.com/hpp/params.php?aaaa/=', 'extra': '', 'sid': '0', 'dir': '_i7/2' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/3' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/4' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': '', 'sid': '0', 'dir': '_i7/5' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': '', 'sid': '0', 'dir': '_i7/6' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': '', 'sid': '0', 'dir': '_i7/7' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/8' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': '', 'sid': '0', 'dir': '_i7/9' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/10' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/11' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/12' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/13' },
    { 'url': 'http://testphp.vulnweb.com/cart.php', 'extra': '', 'sid': '0', 'dir': '_i7/14' },
    { 'url': 'http://testphp.vulnweb.com/cart.php', 'extra': '', 'sid': '0', 'dir': '_i7/15' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/16' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/17' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/18' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i7/19' } ]
  },
  { 'severity': 2, 'type': 30501, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/0' },
    { 'url': 'http://testphp.vulnweb.com/artists.php?artist=1', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/1' },
    { 'url': 'http://testphp.vulnweb.com/categories.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/2' },
    { 'url': 'http://testphp.vulnweb.com/disclaimer.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/3' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/4' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?artist=1', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/5' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=1', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/6' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=02', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/7' },
    { 'url': 'http://testphp.vulnweb.com/login.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/8' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=1', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/9' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=07', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/10' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/11' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/12' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/13' },
    { 'url': 'http://testphp.vulnweb.com/signup.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i8/14' } ]
  },
  { 'severity': 1, 'type': 20101, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/CVS/Repository', 'extra': 'inject behavior', 'sid': '0', 'dir': '_i9/0' },
    { 'url': 'http://testphp.vulnweb.com/CVS/Entries/', 'extra': 'during node type checks', 'sid': '0', 'dir': '_i9/1' },
    { 'url': 'http://testphp.vulnweb.com/hpp/test2', 'extra': 'during path-based dictionary probes', 'sid': '0', 'dir': '_i9/2' } ]
  },
  { 'severity': 0, 'type': 10803, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i10/0' },
    { 'url': 'http://testphp.vulnweb.com/admin/', 'extra': '', 'sid': '0', 'dir': '_i10/1' },
    { 'url': 'http://testphp.vulnweb.com/admin/create.sql', 'extra': '', 'sid': '0', 'dir': '_i10/2' },
    { 'url': 'http://testphp.vulnweb.com/AJAX/.sf/', 'extra': '', 'sid': '0', 'dir': '_i10/3' },
    { 'url': 'http://testphp.vulnweb.com/AJAX/index.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000057v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/4' },
    { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'extra': '', 'sid': '0', 'dir': '_i10/5' },
    { 'url': 'http://testphp.vulnweb.com/CVS/', 'extra': '', 'sid': '0', 'dir': '_i10/6' },
    { 'url': 'http://testphp.vulnweb.com/CVS/Repository', 'extra': '', 'sid': '0', 'dir': '_i10/7' },
    { 'url': 'http://testphp.vulnweb.com/CVS/Entries/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000481v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/8' },
    { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': '', 'sid': '0', 'dir': '_i10/9' },
    { 'url': 'http://testphp.vulnweb.com/Flash/add.fla/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000176v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/10' },
    { 'url': 'http://testphp.vulnweb.com/Flash/add.swf/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000173v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/11' },
    { 'url': 'http://testphp.vulnweb.com/hpp/', 'extra': '', 'sid': '0', 'dir': '_i10/12' },
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=12', 'extra': '', 'sid': '0', 'dir': '_i10/13' },
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=Documents%20and%20Settings', 'extra': '', 'sid': '0', 'dir': '_i10/14' },
    { 'url': 'http://testphp.vulnweb.com/images/', 'extra': '', 'sid': '0', 'dir': '_i10/15' },
    { 'url': 'http://testphp.vulnweb.com/images/logo.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000541v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/16' },
    { 'url': 'http://testphp.vulnweb.com/images/remark.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000545v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/17' },
    { 'url': 'http://testphp.vulnweb.com/medias/', 'extra': '', 'sid': '0', 'dir': '_i10/18' },
    { 'url': 'http://testphp.vulnweb.com/medias/css/', 'extra': '', 'sid': '0', 'dir': '_i10/19' },
    { 'url': 'http://testphp.vulnweb.com/medias/img/', 'extra': '', 'sid': '0', 'dir': '_i10/20' },
    { 'url': 'http://testphp.vulnweb.com/medias/js/', 'extra': '', 'sid': '0', 'dir': '_i10/21' },
    { 'url': 'http://testphp.vulnweb.com/medias/', 'extra': '', 'sid': '0', 'dir': '_i10/22' },
    { 'url': 'http://testphp.vulnweb.com/medias/css/', 'extra': '', 'sid': '0', 'dir': '_i10/23' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'extra': '', 'sid': '0', 'dir': '_i10/24' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/', 'extra': '', 'sid': '0', 'dir': '_i10/25' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/color-printer/', 'extra': '', 'sid': '0', 'dir': '_i10/26' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/network-attached-storage-dlink/', 'extra': '', 'sid': '0', 'dir': '_i10/27' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/web-camera-a4tech/', 'extra': '', 'sid': '0', 'dir': '_i10/28' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/', 'extra': '', 'sid': '0', 'dir': '_i10/29' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/1.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000653v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/30' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/2.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000657v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/31' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/3.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000661v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/32' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/.htaccess', 'extra': '', 'sid': '0', 'dir': '_i10/33' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php', 'extra': '', 'sid': '0', 'dir': '_i10/34' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/35' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/36' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php', 'extra': '', 'sid': '0', 'dir': '_i10/37' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/38' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/details.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/39' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/40' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': '', 'sid': '0', 'dir': '_i10/41' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'extra': '', 'sid': '0', 'dir': '_i10/42' },
    { 'url': 'http://testphp.vulnweb.com/pictures/', 'extra': '', 'sid': '0', 'dir': '_i10/43' },
    { 'url': 'http://testphp.vulnweb.com/pictures/1.jpg/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000460v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/44' },
    { 'url': 'http://testphp.vulnweb.com/pictures/1.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000465v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/45' },
    { 'url': 'http://testphp.vulnweb.com/pictures/2.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000469v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/46' },
    { 'url': 'http://testphp.vulnweb.com/pictures/2.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000433v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/47' },
    { 'url': 'http://testphp.vulnweb.com/pictures/3.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000437v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/48' },
    { 'url': 'http://testphp.vulnweb.com/pictures/3.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000445v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/49' },
    { 'url': 'http://testphp.vulnweb.com/pictures/4.jpg/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000448v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/50' },
    { 'url': 'http://testphp.vulnweb.com/pictures/4.jpg.tn/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000456v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/51' },
    { 'url': 'http://testphp.vulnweb.com/pictures/5.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000441v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/52' },
    { 'url': 'http://testphp.vulnweb.com/pictures/5.jpg.tn/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000452v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/53' },
    { 'url': 'http://testphp.vulnweb.com/pictures/6.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000425v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/54' },
    { 'url': 'http://testphp.vulnweb.com/pictures/7.jpg/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000420v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/55' },
    { 'url': 'http://testphp.vulnweb.com/pictures/7.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000429v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/56' },
    { 'url': 'http://testphp.vulnweb.com/pictures/8.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000409v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/57' },
    { 'url': 'http://testphp.vulnweb.com/pictures/8.jpg.tn/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000349v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/58' },
    { 'url': 'http://testphp.vulnweb.com/pictures/credentials.txt', 'extra': '', 'sid': '0', 'dir': '_i10/59' },
    { 'url': 'http://testphp.vulnweb.com/pictures/ipaddresses.txt', 'extra': '', 'sid': '0', 'dir': '_i10/60' },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-unix.html', 'extra': '', 'sid': '0', 'dir': '_i10/61' },
    { 'url': 'http://testphp.vulnweb.com/pictures/path-disclosure-win.html', 'extra': '', 'sid': '0', 'dir': '_i10/62' },
    { 'url': 'http://testphp.vulnweb.com/pictures/wp-config.bak', 'extra': '', 'sid': '0', 'dir': '_i10/63' },
    { 'url': 'http://testphp.vulnweb.com/pictures/WS_FTP.LOG', 'extra': '', 'sid': '0', 'dir': '_i10/64' },
    { 'url': 'http://testphp.vulnweb.com/secured/.sf/', 'extra': '', 'sid': '0', 'dir': '_i10/65' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000085v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/66' },
    { 'url': 'http://testphp.vulnweb.com/artists.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000517v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/67' },
    { 'url': 'http://testphp.vulnweb.com/cart.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000493v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/68' },
    { 'url': 'http://testphp.vulnweb.com/categories.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000509v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/69' },
    { 'url': 'http://testphp.vulnweb.com/comment.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000153v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/70' },
    { 'url': 'http://testphp.vulnweb.com/comment.php', 'extra': '', 'sid': '0', 'dir': '_i10/71' },
    { 'url': 'http://testphp.vulnweb.com/disclaimer.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000521v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/72' },
    { 'url': 'http://testphp.vulnweb.com/guestbook.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000009v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/73' },
    { 'url': 'http://testphp.vulnweb.com/index.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000513v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/74' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000165v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/75' },
    { 'url': 'http://testphp.vulnweb.com/login.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000037v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/76' },
    { 'url': 'http://testphp.vulnweb.com/privacy.php', 'extra': '', 'sid': '0', 'dir': '_i10/77' },
    { 'url': 'http://testphp.vulnweb.com/product.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000125v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/78' },
    { 'url': 'http://testphp.vulnweb.com/search.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000109v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/79' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': '', 'sid': '0', 'dir': '_i10/80' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': '', 'sid': '0', 'dir': '_i10/81' },
    { 'url': 'http://testphp.vulnweb.com/signup.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000041v335985\x3e', 'extra': '', 'sid': '0', 'dir': '_i10/82' },
    { 'url': 'http://testphp.vulnweb.com/style.css', 'extra': '', 'sid': '0', 'dir': '_i10/83' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i10/84' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i10/85' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i10/86' } ]
  },
  { 'severity': 0, 'type': 10802, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/CVS/Repository', 'extra': 'text/plain', 'sid': '0', 'dir': '_i11/0' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/.htaccess', 'extra': 'text/plain', 'sid': '0', 'dir': '_i11/1' },
    { 'url': 'http://testphp.vulnweb.com/pictures/ipaddresses.txt', 'extra': 'text/plain', 'sid': '0', 'dir': '_i11/2' },
    { 'url': 'http://testphp.vulnweb.com/pictures/wp-config.bak', 'extra': 'text/plain', 'sid': '0', 'dir': '_i11/3' } ]
  },
  { 'severity': 0, 'type': 10801, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/admin/create.sql', 'extra': 'application/javascript', 'sid': '0', 'dir': '_i12/0' },
    { 'url': 'http://testphp.vulnweb.com/Flash/add.fla', 'extra': 'application/binary', 'sid': '0', 'dir': '_i12/1' },
    { 'url': 'http://testphp.vulnweb.com/Flash/add.swf', 'extra': 'application/binary', 'sid': '0', 'dir': '_i12/2' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/3' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/4' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/buy.php?id=$1', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/5' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/6' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/rate.php?id=$1', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/7' },
    { 'url': 'http://testphp.vulnweb.com/pictures/1.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/8' },
    { 'url': 'http://testphp.vulnweb.com/pictures/2.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/9' },
    { 'url': 'http://testphp.vulnweb.com/pictures/3.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/10' },
    { 'url': 'http://testphp.vulnweb.com/pictures/4.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/11' },
    { 'url': 'http://testphp.vulnweb.com/pictures/5.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/12' },
    { 'url': 'http://testphp.vulnweb.com/pictures/6.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/13' },
    { 'url': 'http://testphp.vulnweb.com/pictures/7.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/14' },
    { 'url': 'http://testphp.vulnweb.com/pictures/8.jpg.tn', 'extra': 'image/jpeg', 'sid': '0', 'dir': '_i12/15' },
    { 'url': 'http://testphp.vulnweb.com/pictures/credentials.txt', 'extra': 'application/javascript', 'sid': '0', 'dir': '_i12/16' },
    { 'url': 'http://testphp.vulnweb.com/pictures/WS_FTP.LOG', 'extra': 'text/html', 'sid': '0', 'dir': '_i12/17' },
    { 'url': 'http://testphp.vulnweb.com/privacy.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/18' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/19' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/20' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/21' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/22' },
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i12/23' } ]
  },
  { 'severity': 0, 'type': 10602, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i13/0' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': '', 'sid': '0', 'dir': '_i13/1' } ]
  },
  { 'severity': 0, 'type': 10505, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'text', 'sid': '0', 'dir': '_i14/0' },
    { 'url': 'http://testphp.vulnweb.com/signup.php', 'extra': 'ucc', 'sid': '0', 'dir': '_i14/1' },
    { 'url': 'http://testphp.vulnweb.com/signup.php', 'extra': 'uaddress', 'sid': '0', 'dir': '_i14/2' } ]
  },
  { 'severity': 0, 'type': 10405, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/', 'extra': '', 'sid': '0', 'dir': '_i15/0' },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/.htaccess', 'extra': '', 'sid': '0', 'dir': '_i15/1' },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/server-status', 'extra': '', 'sid': '0', 'dir': '_i15/2' },
    { 'url': 'http://testphp.vulnweb.com/hpp/?pp=Documents%20and%20Settings', 'extra': '', 'sid': '0', 'dir': '_i15/3' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/.htaccess', 'extra': '', 'sid': '0', 'dir': '_i15/4' },
    { 'url': 'http://testphp.vulnweb.com/secured/newuser.php', 'extra': '', 'sid': '0', 'dir': '_i15/5' },
    { 'url': 'http://testphp.vulnweb.com/listproducts.php?cat=02', 'extra': '', 'sid': '0', 'dir': '_i15/6' },
    { 'url': 'http://testphp.vulnweb.com/product.php?pic=07', 'extra': '', 'sid': '0', 'dir': '_i15/7' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i15/8' },
    { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i15/9' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg', 'extra': '', 'sid': '0', 'dir': '_i15/10' },
    { 'url': 'http://testphp.vulnweb.com/showimage.php?file=admin', 'extra': '', 'sid': '0', 'dir': '_i15/11' } ]
  },
  { 'severity': 0, 'type': 10404, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/admin/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/0' },
    { 'url': 'http://testphp.vulnweb.com/CVS/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/1' },
    { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/2' },
    { 'url': 'http://testphp.vulnweb.com/images/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/3' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/4' },
    { 'url': 'http://testphp.vulnweb.com/pictures/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i16/5' } ]
  },
  { 'severity': 0, 'type': 10401, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/.htaccess', 'extra': '', 'sid': '0', 'dir': '_i17/0' },
    { 'url': 'http://testphp.vulnweb.com/privacy.php', 'extra': '', 'sid': '0', 'dir': '_i17/1' } ]
  },
  { 'severity': 0, 'type': 10205, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i18/0' },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i18/1' } ]
  },
  { 'severity': 0, 'type': 10204, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/0' },
    { 'url': 'http://testphp.vulnweb.com/admin/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/1' },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/2' },
    { 'url': 'http://testphp.vulnweb.com/cgi-bin.bak/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/3' },
    { 'url': 'http://testphp.vulnweb.com/CVS/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/4' },
    { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/5' },
    { 'url': 'http://testphp.vulnweb.com/images/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/6' },
    { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/images/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/7' },
    { 'url': 'http://testphp.vulnweb.com/pictures/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i19/8' } ]
  },
  { 'severity': 0, 'type': 10202, 'samples': [
    { 'url': 'http://testphp.vulnweb.com/', 'extra': 'nginx/1.4.1', 'sid': '0', 'dir': '_i20/0' } ]
  }
];

